#include <vector>
#include <cstdint>
#include "ob/common.h"

using Prob = double;        // Probability between 0.0 and 1.0

/*
    Defines the market conditions generated by the simulator.
    Each profile is designed to stress different internal engine components:

    * - AddOnly: Pure insertions. Stresses order-map memory and price-level creation.
    * - CancelHeavy: Adds mixed with cancels. Stresses map lookups and queue unlinking.
    * - CrossingHeavy: Aggressive orders. Stresses the matching loop and trade generation.
    * - HotPrice: Dense clustering. Stresses FIFO queue iteration and CPU cache locality.
    * - WideBook: Sparse orders over a huge range. Stresses level-lookups (e.g., Bitmaps).
    * - Sweep: Massive aggressive orders. Stresses transitions across many price levels.
    * - MixedRealistic: A statistically realistic blend of adds, cancels, and trades.
*/
enum class Workload : uint8_t{
    AddOnly,
    CancelHeavy,
    CrossingHeavy
};

struct SimulatorConfig {
    uint32_t total_events;
    uint32_t random_seed;

    ob::Price min_price;
    ob::Price max_price;
    ob::Price tick_size;
    ob::Price mid_price;

    ob::Quantity min_quantity;
    ob::Quantity max_quantity;

    Prob cancel_prob;
    Prob crossing_prob;
    Prob buy_prob;        

    uint32_t total_hot_price_levels;
    uint32_t initial_book_depth;
    bool valid_events_only;
};

struct SimulatorResult {
    std::vector<ob::Event> events;  
    Workload profile;
    uint32_t seed_used;

    // Metadata
    uint32_t num_add_events = 0;
    uint32_t num_cancel_events = 0;
    uint32_t num_buy_events = 0;
    uint32_t num_resting_orders = 0;
};

SimulatorResult generate_events(Workload profile, const SimulatorConfig& config);